CNN的卷积运算为何使用互相关而不是卷积  
<https://blog.csdn.net/appleyuchi/article/details/86574350>

CNN的卷积运算并非数学定义的卷积  
也就是说，CNN中的运算是不需要翻转卷积核的。  
也就是说，CNN在处理图像时的卷积核是不需要翻转180°的  
我们来用代码看下为什么？  

In [4]:
#-*- coding:utf-8 -*-
#import sys
#reload(sys)
#sys.setdefaultencoding('utf-8')

import numpy as np
A=np.array([[0,0,0,0],\
                [0,0,30,0],\
                [0,60,0,0],\
                [0,0,0,0]])

B=np.array([[0.1,0.01],\
                [1,10]])
import scipy.signal
print("---------卷积结果---------------------")
print(scipy.signal.convolve(A,B,mode='valid'))
print("---------互相关结果---------------------")
print(scipy.signal.correlate(A,B,mode='valid'))

---------卷积结果---------------------
[[0.00e+00 3.00e+00 3.00e-01]
 [6.00e+00 3.06e+01 3.00e+02]
 [6.00e+01 6.00e+02 0.00e+00]]
---------互相关结果---------------------
[[  0.  300.   30. ]
 [600.   60.3   3. ]
 [  0.6   6.    0. ]]


因为卷积层后面连接的是池化层，
也就是说把卷积结果得到的矩阵中，
选取矩阵中数值最大的元素作为保留，矩阵中其余元素一律删除。

所以我们可以看到：
上述代码的
卷积结果中的最大值
与
互相关结果矩阵中的最大值
都是600
因此后面maxpooling层进行池化后得到的值也都是600.

如果后面接全连接层，那么
上面两个矩阵全部flatten以后输入dense层，几乎完全一致，也不影响建模

结论：
CNN中使用卷积或互相关，对于
的贡献是一致的，都是获取像素最大的那个值，
因此可以使用卷积，也可以使用互相关，
但是为了代码的高效，直接使用“互相关”即可。